include: https://gitlab-templates.ddbuild.io/compute-delivery/v2/compute-delivery.yml

test:
  stage: verify
  tags: [ "arch:amd64" ]
  image: registry.ddbuild.io/images/mirror/golang:1.22
  variables:
    GOTOOLCHAIN: "auto"
  script:
    - make test

build-docker-image:
  variables:
    # Pass the version as Docker build arg
    EXTRA_ARGS: --build-arg=VERSION=${CI_COMMIT_TAG}
    IMAGE_NAME: nvidia/container-toolkit
  extends: .build-docker-image
